spring:
  profiles:
    active: prod

  config:
    import: "classpath:application-oauth.yml"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

token:
  expire:
    time: 3600000  # 1시간 (밀리초 단위)

jwt:
  secret: ${JWT_SECRET}
