version: "3.8"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE}
    container_name: ${DOCKER_CONTAINER}
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_LOCATION: /config/application-prod.yml
    volumes:
      - /home/${EC2_USER}/app/config/application-prod.yml:/config/application-prod.yml
    restart: always
    depends_on:
      - ai-service

  ai-service:
    image: ${DOCKERHUB_AI_USERNAME}/${DOCKER_AI_IMAGE}
    container_name: ${DOCKER_AI_CONTAINER}
    restart: always
    ports:
      - "127.0.0.1:8000:8000"